import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

const translations = {
    fr: {
        // Header
        'algerian_library': 'Bibliothèque Algérienne',
        'home': 'Accueil',
        'books': 'Livres',
        'subscribe': 'S\'abonner',
        'dashboard': 'Tableau de bord',
        'admin_dashboard': 'Admin',
        'login': 'Connexion',
        'logout': 'Déconnexion',
        'register': 'S\'inscrire',
        'language': 'Langue',
        'french': 'Français',
        'arabic': 'العربية',
        'search_books': 'Rechercher des livres...',
        'welcome': 'Bienvenue',
        // General
        'loading': 'Chargement...',
        'not_found': 'Page non trouvée',
        'go_home': 'Retour à l\'accueil',
        'details': 'Détails',
        'author': 'Auteur',
        'category': 'Catégorie',
        'availability': 'Disponibilité',
        'available': 'Disponible',
        'unavailable': 'Indisponible',
        'quantity': 'Quantité',
        'description': 'Description',
        'rating': 'Évaluation',
        'rent_book': 'Louer ce livre',
        'login_to_rent': 'Connectez-vous pour louer',
        'actions': 'Actions',
        'edit': 'Modifier',
        'delete': 'Supprimer',
        'save_changes': 'Enregistrer',
        // Subscription
        'choose_plan': 'Choisissez votre plan d\'abonnement',
        'basic_plan': 'Basique',
        'standard_plan': 'Standard',
        'premium_plan': 'Premium',
        'dzd_month': 'DZD/mois',
        'books_per_rental': 'livres par location',
        'rental_duration': 'Durée de location',
        'days': 'jours',
        'renewals': 'renouvellements',
        'reservations': 'Réservations',
        'rare_books_access': 'Accès aux livres rares',
        'subscribe_now': 'S\'abonner maintenant',
        'current_plan': 'Votre plan actuel',
        // E-Card
        'electronic_card': 'Carte Électronique',
        'member_since': 'Membre depuis',
        'subscription_plan': 'Plan d\'abonnement',
        'card_number': 'Numéro de carte',
        'status': 'Statut',
        'active': 'Actif',
        'suspended': 'Suspendu',
        'generate_my_card': 'Générer ma carte',
        'not_subscribed_card': 'Abonnez-vous pour obtenir votre carte électronique.',
        'user_dashboard': 'Tableau de bord',
        'my_rentals': 'Mes locations',
        'my_subscription': 'Mon abonnement',
        'my_ecard': 'Ma E-Carte',
        'card_generated_success': 'Votre E-Carte a été générée avec succès!',
        'card_suspended_success': 'La carte a été suspendue.',
        'card_activated_success': 'La carte a été activée.',
        // Added keys
        'to': 'à',
        'hero_subtitle': 'Votre porte d\'accès à la connaissance et à la culture algérienne et mondiale.',
        'browse_books': 'Parcourir les livres',
        'join_now': 'Rejoignez-nous',
        'featured_books': 'Livres à la une',
        'view_all_books': 'Voir tous les livres',
        'how_it_works': 'Comment ça marche',
        'register_step': 'Inscrivez-vous',
        'register_step_desc': 'Créez un compte en quelques minutes.',
        'subscribe_step': 'Abonnez-vous',
        'subscribe_step_desc': 'Choisissez un plan qui vous convient.',
        'rent_step': 'Louez',
        'rent_step_desc': 'Parcourez et louez vos livres préférés.',
        'read_step': 'Lisez',
        'read_step_desc': 'Profitez de votre lecture !',
        'login_to_account': 'Connectez-vous à votre compte',
        'email_address': 'Adresse e-mail',
        'password': 'Mot de passe',
        'no_account': 'Vous n\'avez pas de compte ?',
        'register_here': 'Inscrivez-vous ici',
        'create_account': 'Créer un nouveau compte',
        'name': 'Nom complet',
        'email': 'Adresse e-mail',
        'confirmPassword': 'Confirmez le mot de passe',
        'nationalId': 'Numéro d\'identité national',
        'phone': 'Téléphone',
        'already_account': 'Vous avez déjà un compte ?',
        'login_here': 'Connectez-vous ici',
        'not_available': 'Non disponible',
        'no_books_found': 'Aucun livre trouvé.',
        // Payment
        'complete_your_subscription': 'Complétez votre abonnement',
        'select_payment_method': 'Sélectionnez un mode de paiement',
        'payment_successful': 'Paiement réussi',
        'subscription_activated': 'Votre abonnement a été activé avec succès !',
        'redirecting': 'Redirection en cours',
        'pay': 'Payer',
        'cancel': 'Annuler',
        'processing': 'Traitement',
        'payment_failed': 'Le paiement a échoué. Veuillez réessayer.',
        'your_e_card': 'Votre E-Carte',
        'download_e_card': 'Télécharger l\'E-Carte',
        'e_card_download_error': 'Erreur lors du téléchargement de l\'E-Carte',
        'go_to_dashboard': 'Aller au tableau de bord',
        'book_not_found': 'Livre non trouvé',
        'reviews': 'avis',
        'rare_book': 'Livre Rare',
        'subscription_desc': 'Débloquez un monde de connaissances avec nos plans flexibles.',
        'due_date': 'Date d\'échéance',
        'end_date': 'Date de fin',
        'manage_subscription': 'Gérer l\'abonnement',
        'no_subscription': 'Vous n\'avez pas d\'abonnement actif.',
        'no_rentals': 'Vous n\'avez aucune location en cours.',
        'total_users': 'Utilisateurs totaux',
        'total_books': 'Livres au total',
        'active_rentals': 'Locations actives',
        'monthly_revenue': 'Revenu mensuel',
        'revenue_over_time': 'Revenus au fil du temps',
        'rentals_per_month': 'Locations par mois',
        'recent_users': 'Utilisateurs récents',
        'pending_rentals': 'Locations en attente',
        'requested': 'a demandé',
        'approve': 'Approuver',
        'reject': 'Rejeter',
        'page_not_found_desc': 'La page que vous recherchez n\'existe pas.',
        // Admin Book Management
        'statistics': 'Statistiques',
        'book_management': 'Gestion des Livres',
        'add_new_book': 'Ajouter un nouveau livre',
        'edit_book': 'Modifier le livre',
        'title_fr': 'Titre (Français)',
        'title_ar': 'Titre (Arabe)',
        'author_fr': 'Auteur (Français)',
        'author_ar': 'Auteur (Arabe)',
        'description_fr': 'Description (Français)',
        'description_ar': 'Description (Arabe)',
        'cover_image_url': 'URL de l\'image de couverture',
        'is_rare': 'Livre rare ?',
        'are_you_sure_delete': 'Êtes-vous sûr de vouloir supprimer ce livre ?',
        'book_saved_success': 'Livre enregistré avec succès.',
        'book_deleted_success': 'Livre supprimé avec succès.',
        // Rental Management
        'rental_management': 'Gestion des locations',
        'pending_requests': 'Demandes en attente',
        'overdue_rentals': 'Locations en retard',
        'mark_as_returned': 'Marquer comme retourné',
        'due': 'Échéance',
        'overdue_by': 'En retard de',
        'days_ago': 'jours',
        'rental_approved_success': 'Location approuvée.',
        'rental_rejected_success': 'Location rejetée.',
        'book_returned_success': 'Livre marqué comme retourné.',
        'estimated_availability': 'Disponibilité estimée',
        'welcome_user': 'Bienvenue,',
        'active_rentals_count': 'Locations Actives',
        'subscription_status': 'Statut d\'Abonnement',
        'due_in': 'Échéance dans',
        'renew': 'Renouveler',
        'demo_accounts': 'Comptes de démo',
        'admin_account': 'Compte Admin',
        'user_account': 'Compte Utilisateur',
        'user': 'Utilisateur',
        'book': 'Livre',
        'rental_date': 'Date de location',
        'no_pending_requests': 'Aucune demande en attente.',
        'no_active_rentals': 'Aucune location active.',
        'no_overdue_rentals': 'Aucune location en retard.',
        'contact': 'Contacter',
        'my_current_rentals': 'Mes locations actuelles',
        // User Management
        'user_management': 'Gestion des utilisateurs',
        'joined_on': 'Inscrit le',
        'card_status': 'Statut de la carte',
        'suspend': 'Suspendre',
        'activate': 'Activer',
        'no_users_found': 'Aucun utilisateur trouvé.',
        // Rack Management
        'rack_management': "Gestion des Rayons",
        'add_new_rack': "Ajouter un rayon",
        'rack_location': "Emplacement du rayon (ex: A1-03)",
        'location': "Emplacement",
        'rack_saved_success': "Rayon enregistré avec succès.",
        'rack_deleted_success': "Rayon supprimé avec succès.",
        'are_you_sure_delete_rack': "Êtes-vous sûr de vouloir supprimer ce rayon ?",
    },
    ar: {
        // Header
        'algerian_library': 'مكتبة الجزائر',
        'home': 'الرئيسية',
        'books': 'الكتب',
        'subscribe': 'اشتراك',
        'dashboard': 'لوحة التحكم',
        'admin_dashboard': 'الإدارة',
        'login': 'تسجيل الدخول',
        'logout': 'تسجيل الخروج',
        'register': 'التسجيل',
        'language': 'اللغة',
        'french': 'Français',
        'arabic': 'العربية',
        'search_books': 'ابحث عن كتب...',
        'welcome': 'مرحباً',
        // General
        'loading': 'جاري التحميل...',
        'not_found': 'الصفحة غير موجودة',
        'go_home': 'العودة إلى الرئيسية',
        'details': 'تفاصيل',
        'author': 'المؤلف',
        'category': 'الفئة',
        'availability': 'التوفر',
        'available': 'متوفر',
        'unavailable': 'غير متوفر',
        'quantity': 'الكمية',
        'description': 'الوصف',
        'rating': 'التقييم',
        'rent_book': 'استعارة هذا الكتاب',
        'login_to_rent': 'سجل الدخول للاستعارة',
        'actions': 'إجراءات',
        'edit': 'تعديل',
        'delete': 'حذف',
        'save_changes': 'حفظ التغييرات',
        // Subscription
        'choose_plan': 'اختر خطة الاشتراك الخاصة بك',
        'basic_plan': 'أساسية',
        'standard_plan': 'عادية',
        'premium_plan': 'ممتازة',
        'dzd_month': 'دج/شهر',
        'books_per_rental': 'كتب لكل استعارة',
        'rental_duration': 'مدة الاستعارة',
        'days': 'أيام',
        'renewals': 'تجديدات',
        'reservations': 'الحجوزات',
        'rare_books_access': 'الوصول إلى الكتب النادرة',
        'subscribe_now': 'اشترك الآن',
        'current_plan': 'خطتك الحالية',
        // E-Card
        'electronic_card': 'البطاقة الإلكترونية',
        'member_since': 'عضو منذ',
        'subscription_plan': 'خطة الاشتراك',
        'card_number': 'رقم البطاقة',
        'status': 'الحالة',
        'active': 'نشط',
        'suspended': 'معلقة',
        'generate_my_card': 'أنشئ بطاقتي',
        'not_subscribed_card': 'اشترك للحصول على بطاقتك الإلكترونية.',
        'user_dashboard': 'لوحة تحكم المستخدم',
        'my_rentals': 'استعاراتي',
        'my_subscription': 'اشتراكي',
        'my_ecard': 'بطاقتي الإلكترونية',
        'card_generated_success': 'تم إنشاء بطاقتك الإلكترونية بنجاح!',
        'card_suspended_success': 'تم تعليق البطاقة.',
        'card_activated_success': 'تم تفعيل البطاقة.',
        // Added keys
        'to': 'إلى',
        'hero_subtitle': 'بوابتك إلى المعرفة والثقافة الجزائرية والعالمية.',
        'browse_books': 'تصفح الكتب',
        'join_now': 'انضم الآن',
        'featured_books': 'كتب مميزة',
        'view_all_books': 'عرض كل الكتب',
        'how_it_works': 'كيف يعمل',
        'register_step': 'سجل',
        'register_step_desc': 'أنشئ حسابًا في دقائق.',
        'subscribe_step': 'اشترك',
        'subscribe_step_desc': 'اختر الخطة التي تناسبك.',
        'rent_step': 'استعر',
        'rent_step_desc': 'تصفح واستعر كتبك المفضلة.',
        'read_step': 'اقرأ',
        'read_step_desc': 'استمتع بقراءتك!',
        'login_to_account': 'تسجيل الدخول إلى حسابك',
        'email_address': 'عنوان البريد الإلكتروني',
        'password': 'كلمة المرور',
        'no_account': 'ليس لديك حساب؟',
        'register_here': 'سجل هنا',
        'create_account': 'إنشاء حساب جديد',
        'name': 'الاسم الكامل',
        'email': 'البريد الإلكتروني',
        'confirmPassword': 'تأكيد كلمة المرور',
        'nationalId': 'رقم الهوية الوطنية',
        'phone': 'الهاتف',
        'already_account': 'هل لديك حساب بالفعل؟',
        'login_here': 'سجل الدخول هنا',
        'not_available': 'غير متوفر',
        'no_books_found': 'لم يتم العثور على كتب.',
        // Payment
        'complete_your_subscription': 'أكمل اشتراكك',
        'select_payment_method': 'اختر طريقة الدفع',
        'payment_successful': 'تم الدفع بنجاح',
        'subscription_activated': 'تم تفعيل اشتراكك بنجاح!',
        'redirecting': 'جاري التوجيه',
        'pay': 'ادفع',
        'cancel': 'إلغاء',
        'processing': 'جاري المعالجة',
        'payment_failed': 'فشلت عملية الدفع. يرجى المحاولة مرة أخرى.',
        'your_e_card': 'بطاقتك الإلكترونية',
        'download_e_card': 'تحميل البطاقة الإلكترونية',
        'e_card_download_error': 'حدث خطأ أثناء تحميل البطاقة الإلكترونية',
        'go_to_dashboard': 'الذهاب إلى لوحة التحكم',
        'book_not_found': 'الكتاب غير موجود',
        'reviews': 'تقييمات',
        'rare_book': 'كتاب نادر',
        'subscription_desc': 'افتح عالمًا من المعرفة من خلال خططنا المرنة.',
        'due_date': 'تاريخ الاستحقاق',
        'end_date': 'تاريخ الانتهاء',
        'manage_subscription': 'إدارة الاشتراك',
        'no_subscription': 'ليس لديك اشتراك نشط.',
        'no_rentals': 'ليس لديك أي استعارات حالية.',
        'total_users': 'إجمالي المستخدمين',
        'total_books': 'إجمالي الكتب',
        'active_rentals': 'الاستعارات النشطة',
        'monthly_revenue': 'الإيرادات الشهرية',
        'revenue_over_time': 'الإيرادات عبر الزمن',
        'rentals_per_month': 'الاستعارات شهريًا',
        'recent_users': 'المستخدمون الجدد',
        'pending_rentals': 'طلبات الاستعارة المعلقة',
        'requested': 'طلب',
        'approve': 'موافقة',
        'reject': 'رفض',
        'page_not_found_desc': 'الصفحة التي تبحث عنها غير موجودة.',
        // Admin Book Management
        'statistics': 'الإحصائيات',
        'book_management': 'إدارة الكتب',
        'add_new_book': 'إضافة كتاب جديد',
        'edit_book': 'تعديل الكتاب',
        'title_fr': 'العنوان (بالفرنسية)',
        'title_ar': 'العنوان (بالعربية)',
        'author_fr': 'المؤلف (بالفرنسية)',
        'author_ar': 'المؤلف (بالعربية)',
        'description_fr': 'الوصف (بالفرنسية)',
        'description_ar': 'الوصف (بالعربية)',
        'cover_image_url': 'رابط صورة الغلاف',
        'is_rare': 'هل الكتاب نادر؟',
        'are_you_sure_delete': 'هل أنت متأكد أنك تريد حذف هذا الكتاب؟',
        'book_saved_success': 'تم حفظ الكتاب بنجاح.',
        'book_deleted_success': 'تم حذف الكتاب بنجاح.',
        // Rental Management
        'rental_management': 'إدارة الاستعارات',
        'pending_requests': 'الطلبات المعلقة',
        'overdue_rentals': 'الاستعارات المتأخرة',
        'mark_as_returned': 'تحديد كمرجع',
        'due': 'تاريخ الاستحقاق',
        'overdue_by': 'متأخر بـ',
        'days_ago': 'أيام',
        'rental_approved_success': 'تمت الموافقة على الاستعارة.',
        'rental_rejected_success': 'تم رفض الاستعارة.',
        'book_returned_success': 'تم تحديد الكتاب كمرجع.',
        'estimated_availability': 'التوفر المقدر',
        'welcome_user': 'مرحباً،',
        'active_rentals_count': 'الاستعارات النشطة',
        'subscription_status': 'حالة الاشتراك',
        'due_in': 'تاريخ الاستحقاق في',
        'renew': 'تجديد',
        'demo_accounts': 'حسابات تجريبية',
        'admin_account': 'حساب المدير',
        'user_account': 'حساب المستخدم',
        'user': 'المستخدم',
        'book': 'الكتاب',
        'rental_date': 'تاريخ الاستعارة',
        'no_pending_requests': 'لا توجد طلبات معلقة.',
        'no_active_rentals': 'لا توجد استعارات نشطة.',
        'no_overdue_rentals': 'لا توجد استعارات متأخرة.',
        'contact': 'تواصل',
        'my_current_rentals': 'استعاراتي الحالية',
        // User Management
        'user_management': 'إدارة المستخدمين',
        'joined_on': 'انضم في',
        'card_status': 'حالة البطاقة',
        'suspend': 'تعليق',
        'activate': 'تفعيل',
        'no_users_found': 'لم يتم العثور على مستخدمين.',
        // Rack Management
        'rack_management': "إدارة الأرفف",
        'add_new_rack': "إضافة رف جديد",
        'rack_location': "موقع الرف (مثال: A1-03)",
        'location': "الموقع",
        'rack_saved_success': "تم حفظ الرف بنجاح.",
        'rack_deleted_success': "تم حذف الرف بنجاح.",
        'are_you_sure_delete_rack': "هل أنت متأكد أنك تريد حذف هذا الرف؟",
    }
};

type Language = 'fr' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('fr');

    useEffect(() => {
        const browserLang = navigator.language.split('-')[0];
        const storedLang = localStorage.getItem('lang') as Language;
        if (storedLang) {
            setLanguage(storedLang);
        } else if (browserLang === 'ar') {
            setLanguage('ar');
        }
    }, []);

    useEffect(() => {
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        localStorage.setItem('lang', language);
    }, [language]);

    const t = (key: string): string => {
        return translations[language][key] || key;
    };
    
    const dir = language === 'ar' ? 'rtl' : 'ltr';

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};